### ISSUE TITLE
Datagram error

### ISSUE THREAD

**Issue by craigy109** [loblao/libpandadna#29]
I seem to get this error no matter what .dna file i compile
AssertionError: _current_index + sizeof(tempvar) <= _datagram->get_length() at line 203 of built/include/datagramIterator.I

**Comment by loblao** [comment]
Mismatched compiler/reader. You should use `script-build` branch, compile and use the C++ reader. Also, recompile all your _.dnas_ with the compiler version in that branch.

**Comment by craigy109** [comment]
the file size goes from 32kb in .dna format to 14kb in .pdna format what am i doing wrong?

**Comment by craigy109** [comment]
C:\Users\Craigy\Desktop\libpandadna-script-build\compiler>python compile.py ttc.
dna -logfile
Reading DNA file... ttc.dna
Writing... ttc.pdna
Done processing ttc.dna.
Done.

**Comment by Puggyblue999** [comment]
If you read README.md, you should know that the purpose of this program is to compile the files to a small, readable binary format. Therefore, it reduces the file format, this isn't a bug!

**Comment by craigy109** [comment]
Sorry I just get the same errors thrown at me with which ever branch I use saying datagram

**Comment by Puggyblue999** [comment]
Today I compiled libpandadna and updated all the .dna files in my resources. Although they're all on the same version, I still get the same error! I think it might not be our faults...

**Comment by craigy109** [comment]
So this is something that is an issue with the code here that needs fixing and not something I'm doing wrong? Hope you guys have a fix

**Comment by Puggyblue999** [comment]
I really don't know what's going on, but I just know I got the same error and everything is updated!

**Comment by craigy109** [comment]
Should I reopen another issue report so loblao can have a look into it?

**Comment by Puggyblue999** [comment]
I think it's worth a try

**Comment by loblao** [comment]
I suspect you're still using the Python parser. Please post the full traceback.

**Comment by Puggyblue999** [comment]
I compiled libpandadna from the script-build branch, put the libpandadna.pyd in the root directory of my game and updated all the .pdna files yet I still get this:

    TTLocalizer: Running in language: english
    from toontown.toonbase.TTLocalizerEnglish import *
    OTPLocalizer: Running in language: english
    from otp.otpbase.OTPLocalizerEnglish import *
    DCFile::read of astron/dclass/otp.dc
    DCFile::read of astron/dclass/toon.dc
    :AstronInternalRepository: Now connecting to 127.0.0.1:7100...
    :AstronInternalRepository: Connecting to gameserver directly (no proxy).
    :AstronInternalRepository: Connecting to //127.0.0.1:7100 via HTTP interface.
    :AstronInternalRepository: Successfully connected to //127.0.0.1:7100.
    :AstronInternalRepository: Connected successfully.
    :AstronInternalRepository: Creating ToontownDistrictAI(401000001)...
    :AstronInternalRepository: Claiming ownership of channel ID: 401000001...
    :AstronInternalRepository: Created ToontownDistrictStats(401000002)
    :AstronInternalRepository: Creating managers...
    :AstronInternalRepository: Creating safe zones...
    :HoodAI: Creating objects... Toontown Central
    Assertion failed: _current_index + size <= _datagram->get_length() at line 143 of c:\repos\panda3d\panda\src\express\datagramIterator.cxx
    Assertion failed: dgi.extract_bytes(5) == "PDNA\n" at line 265 of src\base\DNALoader.cxx
    Traceback (most recent call last):
      File "C:\Panda3D-1.9.0\direct\extensions_native\HTTPChannel_extensions.py", line 36, in doTask
        task.callback(*task.callbackArgs)
      File "C:\Panda3D-1.9.0\direct\distributed\ConnectionRepository.py", line 563,
    in httpConnectCallback
        successCallback(*successArgs)
      File "C:\Panda3D-1.9.0\direct\distributed\AstronInternalRepository.py", line 484, in __connected
        self.handleConnected()
      File "toontown\ai\ToontownAIRepository.py", line 191, in handleConnected
        self.createSafeZones()
      File "toontown\ai\ToontownAIRepository.py", line 138, in createSafeZones
        self.hoods.append(TTHoodAI.TTHoodAI(self))
      File "toontown\hood\TTHoodAI.py", line 17, in __init__
        ToontownGlobals.ToontownCentral)
      File "toontown\hood\HoodAI.py", line 35, in __init__
        dnaData = simbase.air.loadDNAFileAI(dnaStore, dnaFileName)
      File "toontown\ai\ToontownAIRepository.py", line 218, in loadDNAFileAI
        return DNALoader().loadDNAFileAI(dnastore, filename)
    AssertionError: _current_index + size <= _datagram->get_length() at line 143 of c:\repos\panda3d\panda\src\express\datagramIterator.cxx
    :task(error): Exception occurred in PythonTask connect-to-server
    Traceback (most recent call last):
      File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 72, in _run_code
        exec code in run_globals
      File "C:\Users\Joe\Documents\Toonbox\src\toontown\ai\ServiceStart.py", line 53, in <module>
        run()
      File "otp\ai\AIBase.py", line 179, in run
        self.taskMgr.run()
      File "C:\Panda3D-1.9.0\direct\task\Task.py", line 503, in run
        self.step()
      File "C:\Panda3D-1.9.0\direct\task\Task.py", line 461, in step
        self.mgr.poll()
      File "C:\Panda3D-1.9.0\direct\extensions_native\HTTPChannel_extensions.py", line 36, in  doTask
        task.callback(*task.callbackArgs)
      File "C:\Panda3D-1.9.0\direct\distributed\ConnectionRepository.py", line 563, in httpConnectCallback
        successCallback(*successArgs)
      File "C:\Panda3D-1.9.0\direct\distributed\AstronInternalRepository.py", line 484, in __connected
        self.handleConnected()
      File "toontown\ai\ToontownAIRepository.py", line 191, in handleConnected
        self.createSafeZones()
      File "toontown\ai\ToontownAIRepository.py", line 138, in createSafeZones
        self.hoods.append(TTHoodAI.TTHoodAI(self))
      File "toontown\hood\TTHoodAI.py", line 17, in __init__
        ToontownGlobals.ToontownCentral)
      File "toontown\hood\HoodAI.py", line 35, in __init__
        dnaData = simbase.air.loadDNAFileAI(dnaStore, dnaFileName)
      File "toontown\ai\ToontownAIRepository.py", line 218, in loadDNAFileAI
        return DNALoader().loadDNAFileAI(dnastore, filename)
    AssertionError: _current_index + size <= _datagram->get_length() at line 143 of
    c:\repos\panda3d\panda\src\express\datagramIterator.cxx

**Comment by craigy109** [comment]
Heres Mine

 :AstronInternalRepository: Now connecting to 127.0.0.1:7100...
:AstronInternalRepository: Connecting to gameserver directly (no proxy).
:AstronInternalRepository: Connecting to //127.0.0.1:7100 via HTTP interface.
:AstronInternalRepository: Successfully connected to //127.0.0.1:7100.
:AstronInternalRepository: Connected successfully.
:AstronInternalRepository: Creating ToontownDistrictAI(401000001)...
:AstronInternalRepository: Claiming ownership of channel ID: 401000001...
:AstronInternalRepository: Created ToontownDistrictStats(401000002)
:AstronInternalRepository: Creating managers...
:AstronInternalRepository: Creating safe zones...
:HoodAI: Creating objects... Toontown Central
Assertion failed: _current_index + sizeof(tempvar) <= _datagram->get_length() at
 line 203 of c:\repos\panda3d\panda\src\express\datagramIterator.I
Traceback (most recent call last):
  File "C:\Panda3D-1.9.0\direct\extensions_native\HTTPChannel_extensions.py", li
ne 36, in doTask
    task.callback(*task.callbackArgs)
  File "C:\Panda3D-1.9.0\direct\distributed\ConnectionRepository.py", line 563,
in httpConnectCallback
    successCallback(*successArgs)
  File "C:\Panda3D-1.9.0\direct\distributed\AstronInternalRepository.py", line 4
84, in __connected
    self.handleConnected()
  File "toontown\ai\ToontownAIRepository.py", line 191, in handleConnected
    self.createSafeZones()
  File "toontown\ai\ToontownAIRepository.py", line 138, in createSafeZones
    self.hoods.append(TTHoodAI.TTHoodAI(self))
  File "toontown\hood\TTHoodAI.py", line 17, in __init__
    ToontownGlobals.ToontownCentral)
  File "toontown\hood\HoodAI.py", line 35, in __init__
    dnaData = simbase.air.loadDNAFileAI(dnaStore, dnaFileName)
  File "toontown\ai\ToontownAIRepository.py", line 218, in loadDNAFileAI
    return loadDNAFileAI(dnastore, filename)
  File "toontown\dna\DNAParser.py", line 50, in loadDNAFileAI
    data = dnaLoader.loadDNAFileAI(dnaStorage, file)
  File "toontown\dna\DNALoader.py", line 219, in loadDNAFileAI
    self.loadDNAFileBase(dnaStorage, file)
  File "toontown\dna\DNALoader.py", line 209, in loadDNAFileBase
    self.handleStorageData(dgi)
  File "toontown\dna\DNALoader.py", line 130, in handleStorageData
    zoneId = dgi.getUint16()
AssertionError: _current_index + sizeof(tempvar) <= _datagram->get_length() at l
ine 203 of c:\repos\panda3d\panda\src\express\datagramIterator.I
:task(error): Exception occurred in PythonTask connect-to-server
Traceback (most recent call last):
  File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Craigy\Desktop\TTP v3.1 dist\ToontownPlanet\toontown\ai\Service
Start.py", line 53, in <module>
    run()
  File "otp\ai\AIBase.py", line 179, in run
    self.taskMgr.run()
  File "C:\Panda3D-1.9.0\direct\task\Task.py", line 503, in run
    self.step()
  File "C:\Panda3D-1.9.0\direct\task\Task.py", line 461, in step
    self.mgr.poll()
  File "C:\Panda3D-1.9.0\direct\extensions_native\HTTPChannel_extensions.py", li
ne 36, in doTask
    task.callback(*task.callbackArgs)
  File "C:\Panda3D-1.9.0\direct\distributed\ConnectionRepository.py", line 563,
in httpConnectCallback
    successCallback(*successArgs)
  File "C:\Panda3D-1.9.0\direct\distributed\AstronInternalRepository.py", line 4
84, in __connected
    self.handleConnected()
  File "toontown\ai\ToontownAIRepository.py", line 191, in handleConnected
    self.createSafeZones()
  File "toontown\ai\ToontownAIRepository.py", line 138, in createSafeZones
    self.hoods.append(TTHoodAI.TTHoodAI(self))
  File "toontown\hood\TTHoodAI.py", line 17, in __init__
    ToontownGlobals.ToontownCentral)
  File "toontown\hood\HoodAI.py", line 35, in __init__
    dnaData = simbase.air.loadDNAFileAI(dnaStore, dnaFileName)
  File "toontown\ai\ToontownAIRepository.py", line 218, in loadDNAFileAI
    return loadDNAFileAI(dnastore, filename)
  File "toontown\dna\DNAParser.py", line 50, in loadDNAFileAI
    data = dnaLoader.loadDNAFileAI(dnaStorage, file)
  File "toontown\dna\DNALoader.py", line 219, in loadDNAFileAI
    self.loadDNAFileBase(dnaStorage, file)
  File "toontown\dna\DNALoader.py", line 209, in loadDNAFileBase
    self.handleStorageData(dgi)
  File "toontown\dna\DNALoader.py", line 130, in handleStorageData
    zoneId = dgi.getUint16()
AssertionError: _current_index + sizeof(tempvar) <= _datagram->get_length() at l
ine 203 of c:\repos\panda3d\panda\src\express\datagramIterator.I

**Comment by loblao** [comment]
```
File "toontown\dna\DNAParser.py", line 50, in loadDNAFileAI
data = dnaLoader.loadDNAFileAI(dnaStorage, file)
File "toontown\dna\DNALoader.py", line 219, in loadDNAFileAI
self.loadDNAFileBase(dnaStorage, file)
File "toontown\dna\DNALoader.py", line 209, in loadDNAFileBase
self.handleStorageData(dgi)
File "toontown\dna\DNALoader.py", line 130, in handleStorageData
zoneId = dgi.getUint16()
```

@craigy109 
Your code is attempting to use the Python header. You have to port it to use the C++ one, which I cannot help you with.
